package com.expensetracker.unitTests;

import com.expensetracker.auth.JwtUtil;
import com.expensetracker.model.User;
import com.nimbusds.jwt.JWTClaimsSet;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class JwtUtilTest {

    private static final String SECRET = "this-is-a-test-secret-key-that-is-long-enough-for-hs256";
    private static final long ACCESS_EXP_MS = 900_000L;      // 15 min
    private static final long REFRESH_EXP_MS = 604_800_000L; // 7 days

    private JwtUtil jwtUtil;
    private User testUser;

    @BeforeEach
    void setUp() {
        jwtUtil = new JwtUtil(SECRET, ACCESS_EXP_MS, REFRESH_EXP_MS);

        testUser = new User();
        testUser.setEmail("test@example.com");
    }

    @Test
    void generateAccessToken_returnsNonNullNonEmptyToken() {
        String token = jwtUtil.generateAccessToken(testUser);

        assertNotNull(token);
        assertFalse(token.isBlank());
    }

    @Test
    void generateAccessToken_hasThreeDotSeparatedParts() {
        String token = jwtUtil.generateAccessToken(testUser);

        String[] parts = token.split("\\.");
        assertEquals(3, parts.length, "Token should have header, payload, and signature parts");
    }

    @Test
    void generateRefreshToken_returnsNonNullNonEmptyToken() {
        String token = jwtUtil.generateRefreshToken(testUser);

        assertNotNull(token);
        assertFalse(token.isBlank());
    }

    @Test
    void generateAccessToken_and_generateRefreshToken_produceDifferentTokens() {
        String accessToken = jwtUtil.generateAccessToken(testUser);
        String refreshToken = jwtUtil.generateRefreshToken(testUser);

        assertNotEquals(accessToken, refreshToken);
    }

    // --- Regression test for the Nimbus/jjwt mismatch bug ---
    // A token generated by generateAccessToken() must be verifiable by isValid()
    // using the SAME library end-to-end. This was failing before the fix.
    @Test
    void generatedAccessToken_isValid() {
        String token = jwtUtil.generateAccessToken(testUser);

        assertTrue(jwtUtil.isValid(token),
                "A freshly generated access token should be valid — " +
                        "if this fails, generation and verification are using mismatched libraries/keys again.");
    }

    @Test
    void generatedRefreshToken_isValid() {
        String token = jwtUtil.generateRefreshToken(testUser);

        assertTrue(jwtUtil.isValid(token));
    }

    @Test
    void isValid_returnsFalseForMalformedToken() {
        assertFalse(jwtUtil.isValid("not-a-real-token"));
    }

    @Test
    void isValid_returnsFalseForEmptyString() {
        assertFalse(jwtUtil.isValid(""));
    }

    @Test
    void isValid_returnsFalseForNullToken() {
        assertFalse(jwtUtil.isValid(null));
    }

    @Test
    void isValid_returnsFalseForTokenSignedWithDifferentSecret() throws Exception {
        JwtUtil otherUtil = new JwtUtil("a-completely-different-secret-key-value-here", ACCESS_EXP_MS, REFRESH_EXP_MS);
        String tokenFromOtherSecret = otherUtil.generateAccessToken(testUser);

        assertFalse(jwtUtil.isValid(tokenFromOtherSecret),
                "A token signed with a different secret should fail verification");
    }

    @Test
    void isValid_returnsFalseForExpiredToken() throws Exception {
        JwtUtil shortLivedUtil = new JwtUtil(SECRET, 1L, 1L); // 1ms expiry
        String token = shortLivedUtil.generateAccessToken(testUser);

        Thread.sleep(50); // ensure it's expired

        assertFalse(shortLivedUtil.isValid(token));
    }

    @Test
    void parseClaims_returnsCorrectSubject() {
        String token = jwtUtil.generateAccessToken(testUser);

        JWTClaimsSet claims = jwtUtil.parseClaims(token);

        assertEquals("test@example.com", claims.getSubject());
    }

    @Test
    void parseClaims_accessToken_hasTypeAccess() throws Exception {
        String token = jwtUtil.generateAccessToken(testUser);

        JWTClaimsSet claims = jwtUtil.parseClaims(token);

        assertEquals("access", claims.getClaim("type"));
    }

    @Test
    void parseClaims_refreshToken_hasTypeRefresh() throws Exception {
        String token = jwtUtil.generateRefreshToken(testUser);

        JWTClaimsSet claims = jwtUtil.parseClaims(token);

        assertEquals("refresh", claims.getClaim("type"));
    }

    @Test
    void parseClaims_expirationTime_matchesConfiguredExpiry() {
        long beforeGeneration = System.currentTimeMillis();
        String token = jwtUtil.generateAccessToken(testUser);

        JWTClaimsSet claims = jwtUtil.parseClaims(token);
        long actualExpiry = claims.getExpirationTime().getTime();

        // JWT 'exp' is a NumericDate (seconds precision), so up to 999ms
        // gets truncated when the token is serialized — allow for that on both ends.
        long expectedMin = beforeGeneration + ACCESS_EXP_MS - 1000;
        long expectedMax = System.currentTimeMillis() + ACCESS_EXP_MS + 1000;
        System.out.println("actual expiry: "+actualExpiry);
        System.out.println("expected min: "+expectedMin);
        System.out.println("expeceted max: "+expectedMax);
        assertTrue(actualExpiry >= expectedMin && actualExpiry <= expectedMax,
                "Expiration time should be roughly access-token-expiration-ms from generation time");
    }

    @Test
    void parseClaims_throwsForMalformedToken() {
        assertThrows(RuntimeException.class, () -> jwtUtil.parseClaims("garbage.token.value"));
    }
}