package com.expensetracker.auth;

import com.expensetracker.model.User;
import com.nimbusds.jose.JOSEException;
import com.nimbusds.jose.JWSAlgorithm;
import com.nimbusds.jose.JWSHeader;
import com.nimbusds.jose.crypto.MACSigner;
import com.nimbusds.jwt.JWTClaimsSet;
import com.nimbusds.jwt.SignedJWT;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

import java.text.ParseException;
import java.util.Date;

@Service
public class JwtService {

    private final String secret;

    public JwtService(@Value("${JWT_SECRET}") String secret) {
        this.secret = secret;
    }

    public String generateToken(User user) {
        try {
            Date now = new Date();
            Date expiration = new Date(
                    now.getTime() + 1000 * 60 * 60 // 1 hour
            );

            //constructing the payload of the JWT
            JWTClaimsSet claims = new JWTClaimsSet.Builder()
                    .subject(user.getEmail()) //would be better long term to use a ID especially if the email can change
                    .issueTime(now)
                    .expirationTime(expiration)
                    .build();

            //constructing the actual JWT
            //HS256 = HMAC + SHA-256
            SignedJWT signedJWT = new SignedJWT(
                    new JWSHeader(JWSAlgorithm.HS256),
                    claims
            );
            //create signature to say it was generated by this service and not someething else
            //uses the JWT_SECRET in the app.props file to generate the signature to know it was created by this service - in prod should be in a secrete manager
            //the jwt payloads are encoded, not encrypted and an attacker shouldnt have access to secret to generate a valid signature
            //jwts are signed, not encrypted - should not contains sensative information
            signedJWT.sign(new MACSigner(secret));

            return signedJWT.serialize();

        } catch (JOSEException e) {
            throw new RuntimeException("Could not generate JWT", e);
        }
    }

    public String extractEmail(String token) {
        try {
            SignedJWT signedJWT = SignedJWT.parse(token);

            return signedJWT
                    .getJWTClaimsSet()
                    .getSubject();

        } catch (ParseException e) {
            throw new RuntimeException("Invalid JWT", e);
        }
    }
}
